/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemas;

import Model.Product;
import SalesBusinessModel.SalesManager;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author alulab14
 */
public class BuscaProd extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    public int prodSel;
    private JFrame parent = null;
    public BuscaProd() {
        productModel = new MyTableModel();
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_SP.png"));
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 700, 10));

        jLabel1.setText("Buscar por:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setText("Marca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "L'bel", "Esika", "CyºZone" }));
        jComboBox1.setToolTipText("");
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, -1));

        jLabel3.setText("Tipo de Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Labial", "Perfumes", "Cremas", "Sombras", "Desmaquilladoras", "Ropa", "Delineadores", "Rimel", "Desarodorantes", "Shampoo", "Accesorios", "Otros" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, -1));

        jLabel5.setText("Precio mínimo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jTextField1.setText("15.50");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 70, -1));

        jLabel6.setText("Precio máximo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jTextField2.setText("120.20");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 70, -1));

        jCheckBox1.setText("Incluir combos");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel7.setText("Resultados de búsqueda:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_prod.getTableHeader().setResizingAllowed(false);
        tbl_prod.getTableHeader().setReorderingAllowed(false);
        tbl_prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prodMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prod);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 530, 170));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Rango de Precios"));
        jPanel2.setToolTipText("");
        jPanel2.setName("panelRango"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 230, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_prodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prodMouseClicked
     // TODO add your handling code here:
       if (evt.getClickCount() == 2) {
           if(parent != null && parent instanceof Proyecciones){
               Proyecciones pr = (Proyecciones)parent;
               int row = tbl_prod.getSelectedRow();
               String cod = (String)productModel.getValueAt(row, 0);
               pr.setCod(cod);
           }
           if(parent != null && parent instanceof DetallePagina){
               DetallePagina pr = (DetallePagina)parent;
               int row = tbl_prod.getSelectedRow();
               int cod = Integer.parseInt((String)productModel.getValueAt(row, 0));
               String nom= (String)productModel.getValueAt(row, 1);
               pr.setProd(cod,nom);
           }
           if(parent != null && parent instanceof MantenerCombos){
               MantenerCombos comb = (MantenerCombos)parent;
               int row = tbl_prod.getSelectedRow();
               int cod = productModel.productsLst.get(row).getId();
               comb.addProduct(cod);
           }
           setVisible(false);
           //int selRow = tbl_prod.getSelectedRow();
           //int prodId = Integer.parseInt(
	//					tbl_prod.getValueAt(selRow, 0).toString());
           
        }
    }//GEN-LAST:event_tbl_prodMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //buscar
       int indMarca = jComboBox1.getSelectedIndex();
       int indTipo = jComboBox2.getSelectedIndex();
       if(indMarca > 0){
           String brand = "";
           switch(indMarca){
               case 1: brand = "lbel"; break;
               case 2: brand = "esika"; break;
               case 3: brand = "cyzone"; break;
           }
           double minPrice;
           if(!jTextField1.getText().isEmpty()){
           try{
           minPrice = Double.parseDouble(jTextField1.getText());
           double maxPrice = Double.parseDouble(jTextField2.getText());
           if(maxPrice<minPrice){
               JOptionPane.showMessageDialog(null, "introduzca bien el rango de precios");
           }
           else{
               productModel.productsLst = SalesManager.queryProductByPrice(minPrice, maxPrice, brand, indTipo);
           }
           } catch(NumberFormatException num){
               JOptionPane.showMessageDialog(null, "introduzca bien los números de precios");
           }
           } 
           else
                productModel.productsLst = SalesManager.queryProductByBrand(brand, indTipo);
           
       }
       else{
           if(indTipo>0){
               if(!jTextField1.getText().isEmpty()){
                   double minPrice;
                    try{
                        minPrice = Double.parseDouble(jTextField1.getText());
                        double maxPrice = Double.parseDouble(jTextField2.getText());
                        if(maxPrice<minPrice){
                                    JOptionPane.showMessageDialog(null, "introduzca bien el rango de precios");
                        }
                        else{
                            productModel.productsLst = SalesManager.queryProductByPrice(minPrice, maxPrice, "", indTipo);
                        }
                    } catch(NumberFormatException num){
                            JOptionPane.showMessageDialog(null, "introduzca bien los números de precios");
                    }
                } 
                else
                     productModel.productsLst = SalesManager.queryProductByType(indTipo);
           }
           else
               productModel.productsLst = SalesManager.queryAllProducts();
       }
       tbl_prod.setModel(productModel);
           productModel.fireTableChanged(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaProd().setVisible(true);
            }
        });
    }
public javax.swing.JPanel getPanel(){
        return jPanel1;
    }

public void setParent(JFrame parent){
    this.parent = parent;
}

public JFrame getParent(){
    return parent;
}

    class MyTableModel extends AbstractTableModel{
		      ArrayList<Product> productsLst; 
		String [] titles = {"Código", "Nombre", "Tipo de producto", "Precio","Prom Activa"};
		@Override
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return titles.length;
		}

		@Override
		public int getRowCount() {
			// TODO Auto-generated method stub
			return productsLst.size();
		}

		@Override
		public Object getValueAt(int row, int col) {
			String value = "";
			switch(col){
				case 0:  value = "" + productsLst.get(row).getId(); break;
				case 1:  value = productsLst.get(row).getNombre(); break;
                                case 2:  value = "" + productsLst.get(row).getTipoProducto().getNombre(); break;
				case 3:  value = "" + productsLst.get(row).getBasePrice(); break;
				case 4:  value = "" + "si"; break;				
			}
			return value;
		}
		
		public String getColumnName(int col){
			return titles[col];
		}
		
	}
    private MyTableModel productModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbl_prod;
    // End of variables declaration//GEN-END:variables
}
