/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemas;

import Model.Reunion;
import SalesBusinessModel.SalesManager;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author alulab14
 */
public class GenerarAcuerdos extends javax.swing.JFrame {
    
    static void addReu(Reunion reunion) {
        if (model.reunionLst.size()==0){
            model.reunionLst.add(reunion); 
        }
        for (int i=0;i<model.reunionLst.size();i++){
            if (model.reunionLst.get(i).getIdReunion()==reunion.getIdReunion()){
                model.reunionLst.set(i, reunion);
            }else{
               model.reunionLst.add(reunion); 
            }
        }
        
        model.fireTableDataChanged();
    }

    /**
     * Creates new form Template
     */
    public GenerarAcuerdos() {
        
        initComponents();
        initComponents2();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_SP.png"));
        setIconImage(icon);
    }
    public javax.swing.JPanel getPanel(){
        return jPanel1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn1 = new javax.swing.JRadioButton();
        btn2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        btn3 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 700, 10));

        jLabel1.setText("Fecha Desde:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setText("Fecha Hasta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reuniones"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 210));

        buttonGroup1.add(btn1);
        btn1.setText("Listar reuniones pasadas");
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        buttonGroup1.add(btn2);
        btn2.setText("Listar reuniones próximas");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        jCheckBox2.setText("Excel (.xlsx)");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jCheckBox3.setText("Incluir Acuerdos");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        buttonGroup1.add(btn3);
        btn3.setText("Reunión de hoy");
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jButton6.setText("Filtrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed
    public void agregar(){
        det.clear();
        det.setVisible(true);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        det.clear();
        det.setVisible(true);
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    public void modificar(){
        int selRow = jTable1.getSelectedRow();
        
        Reunion r=model.reunionLst.get(selRow);
        det.setValues(r);
        det.setVisible(true);
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selRow = jTable1.getSelectedRow();
        
        Reunion r=model.reunionLst.get(selRow);
        det.setValues(r);
        det.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    public void cancelar(){
        if (jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(new JFrame(), "Selecciona la reunión a elminar");
            return;
        }
        int selRow = jTable1.getSelectedRow();
        int id=model.reunionLst.get(selRow).getIdReunion();
        SalesManager.deleteReunion(id);
        model.reunionLst=SalesManager.queryAllReunion();;
        model.fireTableDataChanged();
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selRow = jTable1.getSelectedRow();
        int id=model.reunionLst.get(selRow).getIdReunion();
        SalesManager.deleteReunion(id);
        model.reunionLst=SalesManager.queryAllReunion();;
        model.fireTableDataChanged();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void acortarFech(LocalDate min, LocalDate max){
        
        ArrayList<Reunion> aux=new ArrayList<Reunion>();
        for (int i =0; i<model.reunionLst.size();i++){
            if (model.reunionLst.get(i).getFecha().compareTo(max)<=0 
                    &&model.reunionLst.get(i).getFecha().compareTo(min)>0 ){
                aux.add(model.reunionLst.get(i));
            }
        }
        model.reunionLst=aux;
        model.fireTableDataChanged();
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jDateChooser1.getDate()==null && 
               buttonGroup1.isSelected(btn1.getModel())==false &&
                buttonGroup1.isSelected(btn2.getModel())==false && 
                buttonGroup1.isSelected(btn3.getModel())==false){
            JOptionPane.showMessageDialog(new JFrame(), "Llena por lo menos un criterio");
            return ;
        }
        if (jDateChooser1.getDate()==null && jDateChooser2.getDate()==null){
            JOptionPane.showMessageDialog(new JFrame(), "Llena el rango completo de fechas");
            return ;
        }
        
        if (buttonGroup1.isSelected(btn1.getModel())){
           acortarFech(LocalDate.MIN,LocalDate.now());
        }
        if (buttonGroup1.isSelected(btn2.getModel())){
           acortarFech(LocalDate.now(),LocalDate.MAX); 
        }
        if (buttonGroup1.isSelected(btn3.getModel())){
            acortarFech(LocalDate.now(),LocalDate.now());
        }
        if (jDateChooser1.getDate()!=null && jDateChooser2!=null){
            Date dat=jDateChooser1.getDate();            
            LocalDate ld1 = LocalDate.parse( new SimpleDateFormat("yyyy-MM-dd").format(dat) );
            Date dat2=jDateChooser1.getDate();
            LocalDate ld2 = LocalDate.parse( new SimpleDateFormat("yyyy-MM-dd").format(dat) );
            acortarFech(ld1,ld2);
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (model.reunionLst.size()==0){
            JOptionPane.showMessageDialog(new JFrame(), "No existe datos a exportar");
            return;
        }
        if (!jCheckBox3.isSelected() && !jCheckBox2.isSelected()){
            JOptionPane.showMessageDialog(new JFrame(), "Seleccione algún formato de salida");
            return;
        }
        String pathSave=null;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int userSelection = fileChooser.showSaveDialog(this);
        File fileToSave=null;
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            fileToSave = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            pathSave=fileToSave.getAbsolutePath();
        }else if (userSelection == JFileChooser.CANCEL_OPTION){
            pathSave=null;
        }

        if (pathSave!=null){
            try {
                // TODO add your handling code here:
                //   Utils.writeToExcell(jTable1,Paths.get("C:\\Temp"));
                //jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seasonalpie.gif"))); // NOI18N
                if (jCheckBox2.isSelected() && jCheckBox3.isSelected()==false){
                    Utils.writeXLSXFile(jTable1,pathSave+"\\reuniones.xlsx");
                   
                }else if(jCheckBox2.isSelected() && jCheckBox3.isSelected()){
                    Utils.writeXLSXFile(jTable1,pathSave+"\\reuniones.xlsx");
                }

            } catch (IOException ex) {
                Logger.getLogger(ReporteVentas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarAcuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarAcuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarAcuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarAcuerdos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarAcuerdos().setVisible(true);
            }
        });
    }

    private void initComponents2() {
        model = new MyTableModel();
        jTable1.setModel(model);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jCheckBox3.setVisible(false);
    }
    class MyTableModel extends AbstractTableModel{
        public ArrayList<Reunion> reunionLst = SalesManager.queryAllReunion(); //SalesManager.queryAllProducts(); 
        
		String [] titles = {"Código", "Área participante", "Tema","Fecha"};
		@Override
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return 4;
		}

		@Override
		public int getRowCount() {
			// TODO Auto-generated method stub
			return reunionLst.size();
		}

		@Override
		public Object getValueAt(int row, int col) {
			String value = "";
			switch(col){
				case 0:  value = "" + reunionLst.get(row).getIdReunion(); break;
				case 1:  value = reunionLst.get(row).getAreaInvolucrada(); break;
				case 2:  value = "" + reunionLst.get(row).getTema(); break;
				case 3:  value = "" + reunionLst.get(row).getFecha(); break;				
			}
			return value;
		}
		
		public String getColumnName(int col){
			return titles[col];
		}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn1;
    private javax.swing.JRadioButton btn2;
    private javax.swing.JRadioButton btn3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private static MyTableModel model;
    private DetalleReunion det=new DetalleReunion(jTable1);
    private boolean first=false;
}
